### ISSUE TITLE
Entering a valid address gives " Invalid address " message in the background. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/greengrainbowl#48] opened 2019-11-01 09:49 UTC
**Describe the bug**
Entering a valid address gives " Invalid address " message in the background. 

**To Reproduce**
1. Go to 'http://greengrainbowl-com.digitaldwarve.staging.wpengine.com/'
2. Click on ' location icon in header '
3. Click on ' search location ' button after you select valid suggestion from dropdown ( here ' bus stand patto centre panjim ' )

**Expected behavior**
The invalid address message should appear only if the input is invalid ( in our case since we choose from the options from the api, we should not display it here as all the options will always be valid )

**Screenshots**
![image](https://user-images.githubusercontent.com/55691499/68016112-d6899180-fcb9-11e9-8e65-896839782800.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]
 - Version [e.g. 78.0.3904.70]

**Smartphone (please complete the following information):**

Device: [e.g. Redmi 3S Prime]
OS [ Android 6.0.1 ]
Browser [e.g. Chrome]
Version [e.g. 75.0.3770.101 ]

**Comment by sujitgawas19** [comment] 2019-11-01 09:57
Duplicate of #39

**Closed by sujitgawas19** 2019-11-01 09:57 UTC
Labels: bug
